authorization_module/authorization_module/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('django.contrib.auth.urls')),
    path('', include('my_auth.urls')),
]

authorization_module/my_auth/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path("logout/", LogoutView.as_view(next_page='login'), name="logout"),
    path('about/', views.about, name='about'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

authorization_module/my_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    mobile = models.CharField(max_length=15, unique=True)
    email_verified = models.BooleanField(default=False)

authorization_module/my_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser
from django.core.validators import RegexValidator


class SignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control form-control-lg'

    username = forms.CharField(max_length=150, required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    first_name = forms.CharField(max_length=20, required=True, widget=forms.TextInput(
        attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=20, required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Last Name'}))
    email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput(
        attrs={'placeholder': 'Email'}))
    mobile = forms.CharField(max_length=15, required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Phone'}), validators=[RegexValidator('^[0-9]*$', message="Phone number should be numeric only.")])
    password1 = forms.CharField(max_length=20, required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(max_length=20, required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name',
                  'mobile', 'email', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Username'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Password'}))

authorization_module/my_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as django_login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from .models import CustomUser as User
from .forms import SignUpForm, LoginForm


# Create your views here.

def signup(request):
    context = {}
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = user.username
            mail_subject = f'{username}, Activate your account.'
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)
            verification_link = request.build_absolute_uri(
                f'/activate/{uid}/{token}')
            message = f'''Hello {username},
            
            Please click the link below to verify your email and complete your registration:
            {verification_link}
            
            Regards,
            Atharva Kulkarni
            '''
            to_email = form.cleaned_data['email']
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            messages.success(
                request, 'Signup successful! Please check your email to verify your account.')
            return render(request, 'confirm_email.html')
        else:
            messages.error(request, form.errors)
            form = SignUpForm()
            context['form'] = form
    else:
        form = SignUpForm()
        context['form'] = form

    return render(request, 'signup.html', context)


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (ValueError, TypeError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.email_verified = True
        user.save()
        django_login(request, user)
        return redirect('about')
    else:
        return render(request, 'activation_invalid.html')


def login(request):
    context = {}
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                django_login(request, user)
                return redirect('about')
            else:
                messages.error(request, 'Username or Password is incorrect.')
                return redirect('login')
        else:
            messages.error(request, form.errors)
            form = LoginForm()
            context['form'] = form
    else:
        form = LoginForm()
        context['form'] = form

    return render(request, 'login.html', context)


@login_required
def about(request):
    if not request.user.is_authenticated:
        return redirect('login')
    else:
        user = User.objects.get(username=request.user.username)
        if not user.email_verified:
            logout(request)
            messages.error(request, 'Please verify your email before login.')
            return redirect('login')
    return render(request, 'about.html')

authorization_module/my_auth/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock title%}

{% block content %}
<!-- <h2>Welcome, {{ request.user.username }}</h2>
<p>Email verification successful.</p>
<p>This is the about page. You're seeing this because you're successfully logged in.</p>
<form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">logout</button>
</form> -->

<section class="vh-100" style="background-color: #c5caf8;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem; background-color: #c2e3eb">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://e0.pxfuel.com/wallpapers/859/112/desktop-wallpaper-clever-abstract-iphone-for-art-lovers-cool-portrait.jpg"
                                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height: 100%; width: 100%;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">
                                <form method="post" action="{% url 'logout' %}">
                                    <h2 class="fw-normal mb-2">Welcome,</h2>
                                    <h1 class="mb-5">{{ request.user.first_name }} {{ request.user.last_name }}</h1>
                                    <p class="mb-5">This is the about page. You're seeing this because you're successfully logged in.</p>
                                    {% csrf_token %}
                                    <div class=" form-outline mb-5">
                                        <button class="btn btn-login btn-lg btn-block" type="submit" id="">Logout</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

authorization_module/my_auth/templates/activation_invalid.html
{% extends 'base.html' %}
{% block title %}Invalid Activation{% endblock title%}

{% block content %}

<section class="vh-100" style="background-color: #c5caf8;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem; background-color: #c2e3eb">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://e0.pxfuel.com/wallpapers/859/112/desktop-wallpaper-clever-abstract-iphone-for-art-lovers-cool-portrait.jpg"
                                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height: 100%; width: 100%;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">
                                <form method="post" action="{% url 'login' %}">
                                    <h2 class="fw-normal mb-2">Invalid Activation!</h2>
                                    <p class="mb-5">Activation link that you clicked is invalid!</p>
                                    {% csrf_token %}
                                    <div class=" form-outline mb-5">
                                        <button class="btn btn-login btn-lg btn-block" type="submit" id="">Login</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

authorization_module/my_auth/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

authorization_module/my_auth/templates/confirm_email.html
{% extends 'base.html' %}
{% block title %}Verify Email{% endblock title%}

{% block content %}
<!-- {% if messages %}
<h2>Please confirm your email address</h2>
<ul class="messages">
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}
<p>We have sent you an email with a link to confirm your email address.</p> -->

<section class="vh-100" style="background-color: #c5caf8;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem; background-color: #c2e3eb">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://e0.pxfuel.com/wallpapers/859/112/desktop-wallpaper-clever-abstract-iphone-for-art-lovers-cool-portrait.jpg"
                                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height: 100%; width: 100%;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">
                                <h3 class="fw-normal mb-4">Account has been created.</h3>
                                <h3 class="fw-normal mb-4">Confirm your Email address.</h3>
                                <p class="mb-4">We have sent you an email with a link to confirm your email address.</p>
                                <p class="mb-4">Please check your email and click on the link to verify your account.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

authorization_module/my_auth/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

<section class="vh-100" style="background-color: #c5caf8;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem; background-color: #c2e3eb">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://e0.pxfuel.com/wallpapers/859/112/desktop-wallpaper-clever-abstract-iphone-for-art-lovers-cool-portrait.jpg"
                                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height: 100%; width: 100%;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">
                                <form method="post">
                                    {% csrf_token %}
                                    <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">
                                        Sign into your account
                                    </h3>
                                    
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}

                                    <div class="form-outline mb-4">
                                        {{ form.username }}
                                    </div>

                                    <div class="form-outline mb-5">
                                        {{ form.password }}
                                    </div>

                                    <div class="pt-1 mb-5">
                                        <button class="btn btn-lg btn-block btn-login" type="submit" id="">Login</button>
                                    </div>

                                    <h5 class="fw-normal mb-5 pb-lg-2 " style="color: #26262a; letter-spacing: 1px;">Don't have an account? <a href="{% url 'signup' %}" style="color: #393f81;">Signup here</a></h5>
                                    <!-- <p class="small text-muted">Atharva Kulkarni <sup>C</sup></p> -->
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

authorization_module/my_auth/templates/signup.html
{% extends "base.html" %}
{% block title %}Signup{% endblock title %}

{% block content %}
<!-- <h2>Signup</h2>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>

<div>
    <label for="id_username">Username:</label>
    <div class="helptext" id="id_username_helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>
    <input type="text" name="username" maxlength="150" autofocus required aria-describedby="id_username_helptext" id="id_username">
</div>
<div>
    <label for="id_first_name">First name:</label>
    <input type="text" name="first_name" maxlength="20" required id="id_first_name">
</div>
<div>
    <label for="id_last_name">Last name:</label>
    <input type="text" name="last_name" maxlength="20" required id="id_last_name">
</div>
<div>
    <label for="id_mobile">Mobile:</label>
    <input type="text" name="mobile" maxlength="15" required id="id_mobile">
</div>
<div>
    <label for="id_email">Email:</label>
    <input type="email" name="email" maxlength="254" required id="id_email">
</div>

<div>
    <label for="id_password1">Password:</label>
    <div class="helptext" id="id_password1_helptext">
        <ul>
            <li>Your password can’t be too similar to your other personal information.</li>
            <li>Your password must contain at least 8 characters.</li>
            <li>Your password can’t be a commonly used password.</li>
            <li>Your password can’t be entirely numeric.</li>
        </ul>
    </div>
    <input type="password" name="password1" autocomplete="new-password" required aria-describedby="id_password1_helptext" id="id_password1">
</div>

<div>
    <label for="id_password2">Password confirmation:</label>
    <div class="helptext" id="id_password2_helptext">Enter the same password as before, for verification.</div>
    <input type="password" name="password2" autocomplete="new-password" required aria-describedby="id_password2_helptext" id="id_password2">
</div> -->

<section class="vh-100" style="background-color: #c5caf8;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem; background-color: #c2e3eb">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://e0.pxfuel.com/wallpapers/859/112/desktop-wallpaper-clever-abstract-iphone-for-art-lovers-cool-portrait.jpg"
                                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height: 100%; width: 100%;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">
                                <form method="post">
                                    {% csrf_token %}
                                    <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">
                                        Signup for an account
                                    </h3>
                                    
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}>Error: {{ message }} </li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                    
                                    <div class="row">
                                        <div class="form-outline mb-4 col-md-6">
                                            {{ form.first_name }}
                                        </div>
                                        
                                        <div class="form-outline mb-4 col-md-6">
                                            {{ form.last_name }}
                                        </div>
                                        
                                        <div class="form-outline mb-4 col-md-6">
                                            {{ form.username }}
                                        </div>
                                        
                                        <div class="form-outline mb-4 col-md-6">
                                            {{ form.mobile }}
                                        </div>
                                        
                                        <div class="form-outline mb-4">
                                            {{ form.email }}
                                        </div>

                                        <div class="form-outline mb-4 col-md-6">
                                            {{ form.password1 }}
                                        </div>
                                        
                                        <div class="form-outline mb-4 col-md-6">
                                            {{ form.password2 }}
                                        </div>
                                        
                                        <small class="helptext mb-2" id="id_password1_helptext">
                                            <ul>
                                                <li>Your password can’t be too similar to your other personal information.</li>
                                                <li>Your password must contain at least 8 characters and not entirely numeric..</li>
                                                <li>Your password can’t be a commonly used password.</li>
                                                <li>Enter the same password as before, for verification.</li>
                                            </ul>
                                        </small>
                                    </div>

                                    <div class="pt-1 mb-5">
                                        <button class="btn btn-lg btn-block btn-login" type="submit" id="">Login</button>
                                    </div>

                                    <h5 class="fw-normal mb-5 pb-lg-2 " style="color: #26262a; letter-spacing: 1px;">Already have an account? <a href="{% url 'login' %}" style="color: #393f81;">Login here</a></h5>
                                    <!-- <p class="small text-muted">Atharva Kulkarni <sup>C</sup></p> -->
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}